apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      imagePullSecrets:
      - name: repo-key  # The secret for pulling the image from a private registry
      containers:
      - name: proxy-container
        image: yxos/proxy
        imagePullPolicy: Always
        ports:
        - containerPort: 5555  # HTTP port
        - containerPort: 1935  # RTMP port

---

apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  selector:
    app: proxy
  type: NodePort
  ports:
  - name: rtmp
    protocol: TCP
    port: 1935
    targetPort: 1935
    nodePort: 31935  # NodePort for RTMP
  - name: http
    protocol: TCP
    port: 5555
    targetPort: 5555
    nodePort: 31555  # NodePort for HTTP
